### ISSUE TITLE
Store Current TX fees for each relevant blockchain on IPFS

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/blockchain-meta#48]
**How It Works Now**

At the moment wallet works with BTC, BCH and ETH blockchains. For each of those a slightly different mechanism is used to obtain current transaction fees. We need to standardize it for all existing blockchains and those that are going to be added in the future.

- BTC: transaction fee data obtained from IPFS. The IPFS populated directly from BCOIN powered block explorer run by HS.

- BCH tx fees are obtained directly from BCOIN node run by HS, despite the fact that data synced to IPFS as well.

- ETC fees are obtained from infura.io. 

As you can see from above there are multiple dependencies i.e. availability of infura.io API, availability of block explorers run by HS, the availability of data on IPFS and so on.

**How It Should Work**

Ideally there should be no dependency other than a single requirement that is "availability of the data on IPFS network". Just like the client retrieves the current exchange rates for different pairs we should look into using a similar implementation for the current transaction fee rates on supported blockchains.

IPFS should provide two values: minimum, optimal and priority fee.

_case 1: transaction fees are available_

The fee slider on send controller will put the priority fee to the highest possible value and the minim to the lowest possible value.

The fee rate should be returned in decimal values of the coin. The client will display those values in fiat (if exchange rate available). However, if rate not available the rate value (in crypto decimals) will be shown i.e 22 sat/byte.

_case 2: transaction fees are not available_

The send controller will use hardcoded values in the app itself. However it's not entirely clear what these values should be. Maybe you can provide some guidelines on what should be the max/min values for a case when the tx fees are not reachable from the client.

**Data Freshness**

The transaction fees should be considered fresh if they are less than 3 minutes old. The proposed 3 minutes interval is fairly random, however imo it should be less than 5 min. I decided to use 3 minutes in order to keep same fresh/outdated logic as for exchange rates.

**Tasks**

- [ ] implement standard transaction fee reference on IPFS for all supported blockchains
- [ ]  provide some guidelines on what should be the max/min values for a case when the tx fees are not reachable from the client
- [ ] consider setting a separate repository here on Github specifically for that purpose. Otherwise, keeping track of it here may become difficult.

**Comment by nk-the-crazy** [comment]
JSON format for Fee estimation is changed. All COIN fees combined into single JSON file.
